### ISSUE TITLE
Disable magic enter entirely

### ISSUE THREAD

**Issue by ezmiller** [subnixr/minimal#16]
I would like to disable the magic enter functionality entirely. It interferes with my writing of git commits when I need to have a blank line. When I tried to set this:

`MNML_MAGICENTER = ()`

I still got some output.

**Comment by subnixr** [comment]
> When I tried to set this:
> `MNML_MAGICENTER = ()`
> I still got some output.

There is a syntax error (spaces around `=`), but in fact I noticed a bug in the initialization of those arrays (i was checking if they were empty rather than unset). I've just pushed the fix on master.

Please, let me know if this does work for you or if your issue relates to widget binding.

**Comment by subnixr** [comment]
The lack of response makes me think this issue is done

**Comment by ezmiller** [comment]
Sorry, this isn't resolved for me, but I couldn't figure out how to get your changes in `master` onto my system. Can you explain the steps and I'll test it today?

**Comment by subnixr** [comment]
It depends on how you configured your system: 

- If you're using zgen or antigen just do `zgen update` (`antigen update`) 
- If you cloned the repo manually just cd into it and do `git pull`

either way, you will see the changes only in new zsh instances, so open a new terminal or type `exec zsh`

**Comment by ezmiller** [comment]
Hi @subnixr I still have the problem even after running `zgen update`. 

![image](https://user-images.githubusercontent.com/772738/41731243-e2ad4b4c-754b-11e8-8a50-fda3143e9cb1.png)

When I hit enter I get the output shown above. This is primarily a problem for me when I'm trying to commit something to get and want to put something in the body of the commit text. When I hit enter it displays the text shown above. If I keep typing, the text that I've entered ends up on the same line as the title of the commit.

**Comment by subnixr** [comment]
ok, try disabling the info line (`MNML_INFOLN=()` in your zshrc)

**Comment by ezmiller** [comment]
I think that did it. Thank you!
